# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk9sk3Z90dyDeXD7Qe8gsWm2GTNK5J0w
"""

import tensorflow as tf

# Create a random tensor of shape (4, 6)
tensor = tf.random.uniform((4, 6))
print("Original Tensor:\n", tensor)

# Find its rank and shape
rank = tf.rank(tensor)
shape = tf.shape(tensor)
print(f"Original Tensor Rank: {rank.numpy()}")
print(f"Original Tensor Shape: {shape.numpy()}")

# Reshape it into (2, 3, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
print("Reshaped Tensor:\n", reshaped_tensor)

# Transpose it to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor:\n", transposed_tensor)

# Broadcast a smaller tensor (1, 4) to match the larger tensor and add them
small_tensor = tf.random.uniform((1, 4))
broadcasted_tensor = tf.broadcast_to(small_tensor, (3, 2, 4))
print("Broadcasted Small Tensor:\n", broadcasted_tensor)

# Add the broadcasted tensor to the transposed tensor
result_tensor = transposed_tensor + broadcasted_tensor
print("Resulting Tensor after Addition:\n", result_tensor)

