# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170OooD2xohSbiyW5GXMTBD4nENdF8tO4
"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

# Define true values (y_true) and model predictions (y_pred)
y_true = np.array([1, 0, 1, 1, 0])
y_pred = np.array([0.9, 0.1, 0.8, 0.3, 0.2])
y_pred_modified = np.array([0.8, 0.2, 0.7, 0.4, 0.3])

# Compute Mean Squared Error (MSE)
mse = tf.keras.losses.MeanSquaredError()
mse_loss = mse(y_true, y_pred).numpy()
mse_loss_modified = mse(y_true, y_pred_modified).numpy()

# Compute Categorical Cross-Entropy (CCE)
cce = tf.keras.losses.CategoricalCrossentropy()
y_true_cce = tf.one_hot(y_true, depth=2)
y_pred_cce = tf.one_hot(y_pred.astype(int), depth=2)
y_pred_modified_cce = tf.one_hot(y_pred_modified.astype(int), depth=2)
cce_loss = cce(y_true_cce, y_pred_cce).numpy()
cce_loss_modified = cce(y_true_cce, y_pred_modified_cce).numpy()

# Print loss values for different predictions
print("Mean Squared Error Loss (Original):", mse_loss)
print("Mean Squared Error Loss (Modified):", mse_loss_modified)
print("Categorical Cross-Entropy Loss (Original):", cce_loss)
print("Categorical Cross-Entropy Loss (Modified):", cce_loss_modified)

# Plot loss function values using Matplotlib
labels = ['MSE', 'CCE']
original_losses = [mse_loss, cce_loss]
modified_losses = [mse_loss_modified, cce_loss_modified]

x = np.arange(len(labels))  # the label locations
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, original_losses, width, label='Original')
rects2 = ax.bar(x + width/2, modified_losses, width, label='Modified')

ax.set_ylabel('Loss Values')
ax.set_title('Loss Values Comparison')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()

fig.tight_layout()

plt.show()

